Nom = input("entrer votre nom : ")
Prenom = input("entrer votre prenom : ")
Age = int(input("entrer votre age : "))
Taille = input("entrer votre taille : ")
print("============FICHE===========")
print("Nom : " + Nom)
print("Prenom : " + Prenom)
print(f"Age : {Age + 1}")
print("Taille : " + Taille)